#ifndef OPTIONSTYPE_H
#define OPTIONSTYPE_H

enum OptionsType
{
    OPTIONS_DUPLICATE = 0,
    OPTIONS_NEW_TABLE = 1,
    OPTIONS_NEW_SUBQUERY = 2,
    OPTIONS_ADD_FROM = 3,
    OPTIONS_ADD_WHERE = 4,
    OPTIONS_ADD_GROUPBY = 5,
    OPTIONS_ADD_HAVING = 6,
    OPTIONS_ADD_ORDERBY = 7,
    OPTIONS_ADD_JOIN = 8,
    OPTIONS_AS = 9,
    OPTIONS_NEW_WHERE_EXPR = 10,

    OPTIONS_LAST
};

#endif // OPTIONSTYPE_H
