#ifndef STRINGS_H
#define STRINGS_H

#include <QString>

static const QString strTextString = "Text/String";
static const QString strNumeric = "Numeric";
static const QString strBoolean = "Boolean";
static const QString strDateTime = "Date/Time";
static const QString strBlob = "Blob/Binary";
static const QString strMisc = "Misc";
static const QString strSpatial = "Spatial";
static const QString strNA = "N/A";

static const QString strDtTextIcon = ":/images/actions/images/small/datatypes_text.png";
static const QString strDtNumericIcon = ":/images/actions/images/small/datatypes_numeric.png";
static const QString strDtMiscIcon = ":/images/actions/images/small/datatypes_misc.png";
static const QString strDtDateTimeIcon = ":/images/actions/images/small/datatypes_datetime.png";
static const QString strDtBoolIcon = ":/images/actions/images/small/datatypes_bool.png";
static const QString strDtBlobIcon = ":/images/actions/images/small/datatypes_blob.png";
static const QString strDtSpatialIcon = ":/images/actions/images/small/datatypes_spatial.png";

static const QString strKeyIcon = ":/images/actions/images/small/key.png";
static const QString strSaveIcon = ":/images/actions/images/actions/filesave.png";
static const QString strApplyIcon = ":/images/actions/images/small/apply.png";
static const QString strAddIcon = ":/images/actions/images/small/add.png";
static const QString strEmptyIcon = ":/images/actions/images/actions/empty_icon.png";
static const QString strTableIcon = ":/images/actions/images/actions/table.png";
static const QString strTablesIcon = ":/images/actions/images/actions/table.png";
static const QString strTableInstIcon = ":/images/actions/images/small/tabinst.png";
static const QString strTableInstLockIcon = ":/images/actions/images/small/tabinstlock.png";
static const QString strProjectOpenIcon = ":/images/actions/images/small/project_open.png";
static const QString strDiagramIcon = ":/images/actions/images/small/diagram.png";
static const QString strDataTypesIcon = ":/images/actions/images/small/datatypes.PNG";
static const QString strCodeIcon = ":/images/actions/images/small/code.png";
static const QString strSqlIcon = ":/images/actions/images/small/sql.png";
static const QString strVersionIcon = ":/images/actions/images/small/arrow-000-medium.png";
static const QString strProcedureIcon = ":/images/actions/images/actions/procedure.png";
static const QString strFunctionTreeIcon = ":/images/actions/images/actions/function_icon.png";
static const QString strRemoveIcon = ":/images/actions/images/small/remove.png";
static const QString strStringsFolder = ":/images/actions/images/big/folder_red.png";
static const QString strIntsFolder = ":/images/actions/images/big/folder_darkblue.png";
static const QString strDateTimesFolder = ":/images/actions/images/big/folder_green.png";
static const QString strBlobFolder = ":/images/actions/images/big/folder_cyan.png";
static const QString strBoolFolder = ":/images/actions/images/big/folder_yellow.png";
static const QString strMiscFolder = ":/images/actions/images/big/folder_brown.png";
static const QString strSpatialFolder = ":/images/actions/images/big/folder_orange.png";
static const QString strDatabaseIcon = ":/images/actions/images/small/database.png";
static const QString strConnectedDatabaseIcon = ":/images/actions/images/small/database_connected.png";
static const QString strDroppedDatabaseIcon = ":/images/actions/images/small/database_dropped.png";
static const QString strDropDatabaseIcon = ":/images/actions/images/small/skull.png";
static const QString strUnConnectedDatabaseIcon = ":/images/actions/images/small/database_cannot_connect.png";
static const QString strFroggieIcon = ":/bigger/images/unaf.png";
static const QString strIcon = ":/bigger/images/big/icon.png";
static const QString strIndexIcon = ":/images/actions/images/small/index.png";
static const QString strWarningIcon = ":/images/actions/images/small/warning.png";
static const QString strRecommendIcon = ":/images/actions/images/small/reccomend.png";
static const QString strViewsIcon = ":/images/actions/images/small/view.png";
static const QString strTriggersIcon = ":/images/actions/images/small/trigger.png";
static const QString strTriggerIcon = ":/images/actions/images/small/trigger.png";
static const QString strCloseIcon = ":/images/actions/images/actions/application_exit.png";
static const QString strWandIcon = ":/images/actions/images/small/wand.png";    // used for the distinct selection
static const QString strNotIcon = ":/images/actions/images/small/not.png";
static const QString strNegIcon = ":/images/actions/images/small/neg.png";
static const QString strMinusIcon = ":/images/actions/images/small/minus.png";
static const QString strFunctionIcon = ":/images/actions/images/small/function.png";
static const QString strBigNotIcon = ":/images/actions/images/big/big_not_icon.png";
static const QString strBigNegIcon = ":/images/actions/images/big/big_neg_icon.png";
static const QString strBigMinusIcon = ":/images/actions/images/big/big_minus_icon.png";
static const QString strParanthesesOpenIcon = ":/images/actions/images/big/parantheses_open.png";
static const QString strParanthesesCloseIcon = ":/images/actions/images/big/parantheses_close.png";
static const QString strXorIcon = ":/images/actions/images/big/big_xor.png";
static const QString strLeftShiftIcon = ":/images/actions/images/big/big_leftshift.png";
static const QString strRightShiftIcon = ":/images/actions/images/big/big_rightshift.png";
static const QString strBinaryOrIcon = ":/images/actions/images/big/big_binary_or.png";
static const QString strBinaryAndIcon = ":/images/actions/images/big/big_binary_and.png";
static const QString strPlusIcon = ":/images/actions/images/big/big_plus.png";
static const QString strDivideIcon = ":/images/actions/images/big/big_divide.png";
static const QString strModuloIcon = ":/images/actions/images/big/big_modulo.png";
static const QString strMultiplyIcon = ":/images/actions/images/big/big_multiply.png";
static const QString strEqualIcon = ":/images/actions/images/big/big_equal.png";
static const QString strGreaterOrEqualIcon = ":/images/actions/images/big/big_greater_or_equal.png";
static const QString strLessOrEqualIcon = ":/images/actions/images/big/big_less_or_equal.png";
static const QString strGreaterIcon = ":/images/actions/images/big/big_greater.png";
static const QString strLessIcon = ":/images/actions/images/big/big_less.png";
static const QString strNotEqIcon = ":/images/actions/images/big/big_noteq.png";
static const QString strNotEq1Icon = ":/images/actions/images/big/big_noteq_1.png";
static const QString strNotEqNullSafeIcon = ":/images/actions/images/big/big_noteq_nullsafe.png";
static const QString strColumnIcon = ":/images/actions/images/small/table-select-column-icon.png";
static const QString strTypeHereIcon = ":/images/actions/images/small/type_here.png";
static const QString strAliasIcon = ":/images/actions/images/small/alias.png";
static const QString strOrderIcon = ":/images/actions/images/small/edit_list_order.png";
static const QString strForeignKeyIcon = ":/images/actions/images/small/foreign_key.png";
static const QString strTriggerUpdateIcon = ":/images/actions/images/small/trigger_update.png";
static const QString strTriggerDeleteIcon = ":/images/actions/images/small/delete_table_row.png";
static const QString strTriggerInsertIcon = ":/images/actions/images/small/insert_table_row.png";
static const QString strTriggerBeforeIcon = ":/images/actions/images/small/before.png";
static const QString strTriggerAfterIcon = ":/images/actions/images/small/after.png";
static const QString strRecreateDatabaseIcon = ":/images/actions/images/small/agt_reload.png";
static const QString strConnectConnectionIcon = ":/images/actions/images/small/connect.png";
static const QString strBrowseConnectionIcon = ":/images/actions/images/small/folder_explore.png";
static const QString strEditConnectionIcon = ":/images/actions/images/small/pencil3.png";

static const QString NEW_TABLE = "New table reference";
static const QString NEW_COLUMN = "New column";
static const QString DUPLICATE = "Duplicate";
static const QString ADD_FROM = "FROM...";
static const QString ADD_WHERE = "WHERE...";
static const QString NEW_SUBQUERY = "New subquery";
static const QString ADD_GROUPBY = "GROUP BY...";
static const QString ADD_HAVING = "HAVING...";
static const QString ADD_ORDERBY = "ORDER BY...";
static const QString ADD_JOIN = "JOIN ...";
static const QString ADD_ALIAS = "AS...";
static const QString ADD_WHERE_EXPRESSION_OR = "OR ...";
static const QString ADD_WHERE_EXPRESSION_AND = "AND ...";
static const QString ADD_WHERE_EXPRESSION = "New expression ...";
static const QString strRemove = "REMOVE";
static const QString strMathMinus = "MINUS";
static const QString strMathPlus = "PLUS";
static const QString strMathMultiply = "MULTPILY";
static const QString strMathDivide = "DIVIDE";
static const QString strMathMod = "MOD";
static const QString strMathDiv = "DIV";

static const QString strLogNot = "NOT";
static const QString strLogNeg = "NEG";
static const QString strLogXor = "XOR";
static const QString strLogLShift = "Left Shift";
static const QString strLogRShift = "Right Shift";
static const QString strLogOr = "OR";
static const QString strLogAnd = "AND";

static const QString strCmpEqual = "Equal";
static const QString strCmpNotEqual = "Not Equal";
static const QString strCmpLess = "Less";
static const QString strCmpGreater = "Greater";
static const QString strCmpLessOrEqual = "Less or Equal";
static const QString strCmpGreaterOrEqual = "Greater or Equal";

static const QString strLike = "LIKE";
static const QString strIn = "IN";
static const QString strIs = "IS";
static const QString strExists = "EXISTS";
static const QString strBetween = "BETWEEN";
static const QString strNotText = "NOT_TEXT";
static const QString strDistinct = "DISTINCT";
static const QString strStar = "*";
static const QString strRollup = "ROLLUP";
static const QString strNull = "NULL";

static const QString strLShiftOp = "<<";
static const QString strRShiftOp = ">>";
static const QString strOrOp = "|";
static const QString strAndOp = "&";
static const QString strNegOp = "~";
static const QString strXorOp = "^";
static const QString strMinusOp = "-";
static const QString strPlusOp = "+";
static const QString strMulOp = "*";
static const QString strDivOp = "/";
static const QString strModOp = "%";
static const QString strDivTOp = "DIV";
static const QString strEqOp = "=";
static const QString strNEqOp = "!=";
static const QString strLessOp = "<";
static const QString strGrOp = ">";
static const QString strLEOp = "<=";
static const QString strGEOp = ">=";
static const QString strNotOp = "!";

static const QString strOpenParantheses = "(";
static const QString strCloseParantheses = ")";

static const QString strActionIndexSeparator = "^";

static const QString strYes = "Yes";
static const QString strNo = "No";

static const QString strNewLineBetweenSelectExpressionsInSqlGeneration = "NewLineBetweenSelectExpressionsInSqlGeneration";
static const QString strUnauthorizedFrog = "The Unauthorized Frog";
static const QString strDDM = "Database Deployment Manager";
static const QString strDrawTableTypes = "DrawTableTypes";
static const QString strAllowFkPropagation = "AllowFkPropagation";
static const QString strUseDefaultLengths = "UseDefaultLengths";
static const QString strContinuousValidation = "ContinuousValidation";
static const QString strCase = "Case";
static const QString strBackticks = "Backticks";
static const QString strGenerateComments = "GenerateComments";
static const QString strPKSposition = "PKSposition";
static const QString strFKSposition = "FKSposition";
static const QString strSqlDelimiterText = "Delimiter";
static const QString strSqlDelimiter = "//";
static const QString strLower = "Lower";
static const QString strUpper = "Upper";
static const QString strColumnDeclaration = "ColumnDeclaration";
static const QString strInTable = "InTable";
static const QString strConnectionsCount = "ConnectionsCount";
static const QString strName = "Name";
static const QString strHost = "Host";
static const QString strPass = "Pass";
static const QString strUser = "User";
static const QString strDB = "DB";
static const QString strAutoConnect = "AutoConnect";
static const QString strDbType = "DbType";

static const QString strMru1 = "mru1";
static const QString strMru2 = "mru2";
static const QString strMru3 = "mru3";
static const QString strMru4 = "mru4";
static const QString strMru5 = "mru5";

static const QString browsedTablePrefix = "B:";
static const QString browsedViewPrefix = "V:";
static const QString browsedProcPrefix = "P:";
static const QString browsedFuncPrefix = "F:";
static const QString strSpace = " ";
static const QString strNewline = "\n";
static const QString strSemicolon = ";";
static const QString strUnderline = "_";
static const QString strAutoIdx = "autoidx";

#endif // STRINGS_H
