HEADERS += query_builder/qbr_CellAsCommand.h                          \
        query_builder/qbr_CellQuerySmallOptionsBox.h                  \
        query_builder/qbr_QueryAsGenerator.h                          \
        query_builder/qbr_QueryTextInputItem.h                        \
        query_builder/qbr_SelectQuerySelectComponent.h                \
        query_builder/qbr_CellClose.h                                 \
        query_builder/qbr_CellSelectCommand.h                         \
        query_builder/qbr_QueryComponents.h                           \
        query_builder/qbr_SelectQueryAsComponent.h                    \
        query_builder/qbr_SelectQueryWhereComponent.h                 \
        query_builder/qbr_CellCommand.h                               \
        query_builder/qbr_CellTableChooser.h                          \
        query_builder/qbr_QueryGraphicsHelper.h                       \
        query_builder/qbr_SelectQueryFromComponent.h                  \
        query_builder/qbr_SingleExpressionQueryComponent.h            \
        query_builder/qbr_CellForSingleExpression.h                   \
        query_builder/qbr_CellTable.h                                 \
        query_builder/qbr_QueryGraphicsItem.h                         \
        query_builder/qbr_SelectQueryGraphicsItem.h                   \
        query_builder/qbr_TableGraphicsItem.h                         \
        query_builder/qbr_CellFromCommand.h                           \
        query_builder/qbr_CellTypeChooser.h                           \
        query_builder/qbr_QueryGraphicsScene.h                        \
        query_builder/qbr_SelectQueryGroupByComponent.h               \
        query_builder/qbr_TableQueryComponent.h                       \
        query_builder/qbr_CellGroupByCommand.h                        \
        query_builder/qbr_CellWhereCommand.h                          \
        query_builder/qbr_QueryGraphicsView.h                         \
        query_builder/qbr_SelectQuery.h                               \
        query_builder/qbr_CellJoinCommand.h                           \
        query_builder/qbr_DatabaseFunctionInstantiationComponent.h    \
        query_builder/qbr_Query.h                                     \
        query_builder/qbr_SelectQueryJoinComponent.h                  \
        query_builder/qbr_CellOrderByCommand.h                        \
        query_builder/qbr_OptionTypes.h                               \
        query_builder/qbr_QueryItemListDialog.h                       \
        query_builder/qbr_SelectQueryOrderByComponent.h

SOURCES += query_builder/qbr_CellAsCommand.cpp                        \
        query_builder/qbr_CellQuerySmallOptionsBox.cpp                \
        query_builder/qbr_QueryComponents.cpp                         \
        query_builder/qbr_SelectQueryAsComponent.cpp                  \
        query_builder/qbr_SelectQueryWhereComponent.cpp               \
        query_builder/qbr_CellClose.cpp                               \
        query_builder/qbr_CellSelectCommand.cpp                       \
        query_builder/qbr_Query.cpp                                   \
        query_builder/qbr_SelectQuery.cpp                             \
        query_builder/qbr_SingleExpressionQueryComponent.cpp          \
        query_builder/qbr_CellCommand.cpp                             \
        query_builder/qbr_CellTableChooser.cpp                        \
        query_builder/qbr_QueryGraphicsHelper.cpp                     \
        query_builder/qbr_SelectQueryFromComponent.cpp                \
        query_builder/qbr_TableGraphicsItem.cpp                       \
        query_builder/qbr_CellForSingleExpression.cpp                 \
        query_builder/qbr_CellTable.cpp                               \
        query_builder/qbr_QueryGraphicsItem.cpp                       \
        query_builder/qbr_SelectQueryGraphicsItem.cpp                 \
        query_builder/qbr_TableQueryComponent.cpp                     \
        query_builder/qbr_CellFromCommand.cpp                         \
        query_builder/qbr_CellTypeChooser.cpp                         \
        query_builder/qbr_QueryGraphicsScene.cpp                      \
        query_builder/qbr_SelectQueryGroupByComponent.cpp             \
        query_builder/qbr_CellGroupByCommand.cpp                      \
        query_builder/qbr_CellWhereCommand.cpp                        \
        query_builder/qbr_QueryGraphicsView.cpp                       \
        query_builder/qbr_SelectQueryJoinComponent.cpp                \
        query_builder/qbr_CellJoinCommand.cpp                         \
        query_builder/qbr_DatabaseFunctionInstantiationComponent.cpp  \
        query_builder/qbr_QueryItemListDialog.cpp                     \
        query_builder/qbr_SelectQueryOrderByComponent.cpp             \
        query_builder/qbr_CellOrderByCommand.cpp                      \
        query_builder/qbr_QueryAsGenerator.cpp                        \
        query_builder/qbr_QueryTextInputItem.cpp                      \
        query_builder/qbr_SelectQuerySelectComponent.cpp

