.\" Copyright (C) 2010-2012 The Unauthorized Frog Project
.\" Author: Ferenc Deak <fritzone@gmail.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH DDM 1 "Jan 11, 2013"
.SH NAME
ddm \- Database Deployment Manager
.SH SYNOPSIS
.B ddm
.SH DESCRIPTION
Database Deployment Manager (ddm) is an application to create, manage,
browse and deploy databases. The target audience of it are database
administrators, programmers or hobbyists who want to know more about
how to create the startup layout of a database, and learn more about
the process itself.

The application comes with an extensive built in help, consult that
for further references.
.SH OPTIONS
.TP
.SH BUGS
If you find a bug, please report it to fritzone@gmail.com
.PP
